apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: "014498634556.dkr.ecr.ap-south-1.amazonaws.com/uat-bhrc-auth:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 3003
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: auth
  ports:
    - port: 80
      targetPort: 3003
  type: ClusterIP
