apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tenant
  template:
    metadata:
      labels:
        app: tenant
    spec:
      containers:
        - name: tenant
          image: "014498634556.dkr.ecr.ap-south-1.amazonaws.com/uat-bhrc-tenant:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: tenant
spec:
  selector:
    app: tenant
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP
