apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient
spec:
  replicas: 3
  selector:
    matchLabels:
      app: patient
  template:
    metadata:
      labels:
        app: patient
    spec:
      containers:
        - name: patient
          image: 014498634556.dkr.ecr.ap-south-1.amazonaws.com/uat-bhrc-patient:20260223114127
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: patient
spec:
  selector:
    app: patient
  ports:
    - port: 80
      targetPort: 3001
  type: ClusterIP
  template:
    spec:
      containers:
        - image: 014498634556.dkr.ecr.ap-south-1.amazonaws.com/uat-bhrc-patient:20260223114127
